[project]
name = "ollama-stop"
description = "Passthrough node that instantly unloads any running ollama model mid workflow. No API calls, just accepts plain string as a model name and executes 'ollama stop <model>' command in your system."
version = "1.0.0"
license = {file = "LICENSE"} 
classifiers = [
     "Operating System :: OS Independent"
]


[project.urls]
Repository = "https://github.com/bhhtr12/ComfyUI-ollama-stop"
#  Used by Comfy Registry https://registry.comfy.org
Documentation = "https://github.com/bhhtr12/ComfyUI-ollama-stop/wiki"
"Bug Tracker" = "https://github.com/bhhtr12/ComfyUI-ollama-stop/issues"

[tool.comfy]
PublisherId = "bhhtr12"
DisplayName = "ComfyUI-ollama-stop"
Icon = ""
includes = [] 
# "requires-comfyui" = ">=1.0.0"  # ComfyUI version compatibility

